### ISSUE TITLE
Getting XPluginStart callback Missing Error

### ISSUE THREAD

**Issue by DaveVanB** [xpnteam/xpnet#25]
I'm trying to run the sample plugins in XP-11 and get the following error in the X-Plane log.txt:

Failed: C:\SIMs/X-Plane 11/Resources/plugins/XPNetTest/64/win.xpl.  (This file is a loadable DLL but is missing the XPluginStart callback.)

I've tried using .NET Core 2.1 and 3.1 with the same results.  I added all the DLLs based on one of the Closed Issues solutions, but that doesn't help either.
Help would be much appreciated.
Thanks,
Dave

**Comment by jaurenq** [comment]
I haven't run across that problem.  How did you build the project?  From within Visual Studio or using the Makefiles?  Did you see any errors or warnings during the project build?

**Comment by DaveVanB** [comment]
Stephen,

Thanks for getting back to me.

I’ve tried several different ways of building the project, all within Visual Studio 2019.  In one case, I just loaded the XPNet solution into VS2019 and ran Build on the XPNet.LoggerPlugin project.  That resulted in the following content in the Debug folder:



I then copied all those files to the X-Plane plugins folder path of …./plugins/XPNet/64 and changed the name of XPNet.LoggerPlugin.dll to win.xpl.



 

Then I start X-Plane, let it run for a few seconds and then shutdown.

Looking at the Log.txt file after shutdown I have the following related to the XPNet plugin:

 

XPluginStart : Error Code = 127 : The specified procedure could not be found.

XPluginStop : Error Code = 127 : The specified procedure could not be found.

XPluginEnable : Error Code = 127 : The specified procedure could not be found.

XPluginDisable : Error Code = 127 : The specified procedure could not be found.

XPluginReceiveMessage : Error Code = 127 : The specified procedure could not be found.

Failed: C:\SIMs/X-Plane 11/Resources/plugins/XPNet/64/win.xpl.  (This file is a loadable DLL but is missing the XPluginStart callback.)

 

I suspect I’m doing something wrong, but can’t figure out what it might be.

 

Thanks again for any help you can provide.

Regards,

Dave

**Comment by DaveVanB** [comment]
Stephen,

Here’s the output from the Build.  No errors or warnings.

 

1>------ Build started: Project: XPNet.CLR, Configuration: Debug Any CPU ------

1>XPNet.CLR -> C:\XDev2019\xpnet-master\XPNet.CLR\bin\Debug\netcoreapp2.1\XPNet.CLR.dll

2>------ Build started: Project: XPNet.LoggerPlugin, Configuration: Debug Any CPU ------

2>XPNet.LoggerPlugin -> C:\XDev2019\xpnet-master\XPNet.LoggerPlugin\bin\Debug\netcoreapp2.1\XPNet.LoggerPlugin.dll

========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

 

Thanks,

Dave

**Comment by DaveVanB** [comment]
Well, I figured out what I was doing wrong and will post it here for others.
_**READ AND FOLLOW THE ENTIRE README INSTRUCTIONS**_
You really do have to use the Command Prompt to set up the project and then after building, you use the command prompt to publish the project.  This step adds all the .NET Core dlls, etc. that are necessary to make the plugin work.

Thanks for a great tool!
Dave
